better init script

diff --git a/securitycloud/files/packaging/ipfixcol.init b/securitycloud/files/packaging/ipfixcol.init
--- a/securitycloud/files/packaging/ipfixcol.init
+++ b/securitycloud/files/packaging/ipfixcol.init
@@ -1,91 +1,85 @@
-#!/bin/bash
-#
-# ipfixcol IPFIX collector
-#
-# chkconfig: - 90 60
-# description: IPFIX flow collector
-# processname: ipfixcol
-# pidfile: /var/run/ipfixcol.pid
-  
-prog="ipfixcol"
-params="-v 2"
-user="ipfixcol"
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          ipfixcol
+# Required-Start:    $network $remote_fs $syslog
+# Required-Stop:     $network $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: ipfixcol
+# Description:       ipfixcol
+### END INIT INFO
 
-start() {
-	# Check whether ipfixcol is running
-	if status; then
-		echo "$prog is already running"
-		return 1
-	fi
+DESC="ipfixcol"
+NAME=ipfixcol
 
-	# Start ipfixcol
-	echo "Starting $prog..."
-	su -c "$prog $params -d > /dev/null" $user
-	retval=$?
+IPFIXCOLD=ipfixcol
+IPFIXCOLD_OPTIONS="-v 2"
+DAEMON=/usr/local/bin/ipfixcol
+PIDFILE=/var/run/ipfixcol.pid
+WORKDIR=/var/lib/ipfixcol
+USER="ipfixcol"
 
-	return $retval
+SCRIPTNAME=/etc/init.d/$NAME
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Define LSB log_* functions.
+. /lib/lsb/init-functions
+
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   other if daemon could not be started or a failure occured
+	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON --chuid $USER --chdir $WORKDIR -- $IPFIXCOLD_OPTIONS
 }
 
-stop() {
-	if ! status; then
-		echo "$prog is NOT running"
-		return 1
-	fi
-
-	echo "Stopping $prog..."
-
-	# Stop ipfixcol; identify all involved PIDs and kill each of them
-	pids=( $(pgrep $prog) )
-	for pid in "${pids[@]}"; do
-		if [[ $pid != $$ ]]; then
-			kill "$pid"
-		fi
-	done
-
-	retval=$?
-
-	return $retval
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   other if daemon could not be stopped or a failure occurred
+	start-stop-daemon --stop --quiet --remove-pidfile --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
 }
-
-# Prints output when first argument is '1'
-status() {
-	ps -eo command | grep "^$prog $params" > /dev/null
-	retval=$?
-	if [ "$#" -eq 1 ] && [ "$1" -eq 1 ]; then
-		if [ "$retval" -eq 0 ]; then
-			echo "$prog is running"
-		else
-			echo "$prog is NOT running"
-		fi
-	fi
-
-	return $retval
-}
-
-restart() {
-	stop
-	start
-}	
 
 case "$1" in
-	start)
-		start
-	;;
-	stop)
-		stop
-	;;
-	restart)
-		restart
-	;;
-	reload)
-		restart
-	;;
-	status)
-		status 1
-	;;
-	*)
-		echo "Usage: $0 {start|stop|status|restart}"
-		exit 1
-esac
+  start)
+	log_daemon_msg "Starting $DESC" "$IPFIXCOLD"
+	do_start
+	case "$?" in
+		0) log_end_msg 0 ;;
+		1) log_progress_msg "already started"
+		   log_end_msg 0 ;;
+		*) log_end_msg 1 ;;
+	esac
 
-exit $?
+	;;
+  stop)
+	log_daemon_msg "Stopping $DESC" "$IPFIXCOLD"
+	do_stop
+	case "$?" in
+		0) log_end_msg 0 ;;
+		1) log_progress_msg "already stopped"
+		   log_end_msg 0 ;;
+		*) log_end_msg 1 ;;
+	esac
+
+	;;
+  restart|force-reload)
+	$0 stop
+	$0 start
+	;;
+  status)
+	status_of_proc -p $PIDFILE $DAEMON $IPFIXCOLD && exit 0 || exit $?
+	;;
+  *)
+	echo "Usage: $SCRIPTNAME {start|stop|rotate|restart|force-reload|status}" >&2
+	exit 3
+	;;
+esac
